### ISSUE TITLE
Display text inside the dots

### ISSUE THREAD

**Issue by Edvardunsvag** [Milad-Akarie/smooth_page_indicator#49]
Hello. Great work with the package. It would be a very neat feature to add a title option to the dots. This way you would be able to display the pagenumber for instance, instead of just showing dots.

Looking forward to hearing from you.

**Comment by mikhael28** [comment]
I will +1 this issue - it would be very nice indeed! As nice and as simple as this package is to implement (I'm using it in two different parts of my project) I'm going to have to remove it and swap it with something I hand-roll or another package, mostly because having the ability to display a custom element within the Swap Effect is mission critical to allowing anything more than the most basic navigation.

**Comment by mikhael28** [comment]
For example, this package seems to support custom child Elements that would support such a use-case. https://pub.dev/packages/page_view_indicators
